### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by PabloGN** [brainstudio-team/NeMo#3]
Hi, I would like to tell you that I used this software in the past but I saw no improvements from the Sourceforge site and I abandoned in favour of [genn-team/genn](https://github.com/genn-team/genn)
Each system has its weaknesses and strengths, so I would like to know if you are going to "maintain alive" this project.
I hope we can collaborate in this project.

**Comment by zfountas** [comment]
Dear Pablo,

Thank you for your message! This project is currently being (slowly) maintained by a small team that comprises mainly myself and @pmediano. We are part of the computational neurodynamics group at Imperial College, where this project started, but unfortunately the main author of NeMo is not working with us anymore. This is why the core functionality has not been improved for a while. Since the Sourceforge site, we have mainly:

- improved the documentation and the python interface (thanks to @pmediano), 
- added the ability to use multiple computers in the same simulation via MPI (thanks to a student), and
- been developing a graphical user interface called "brain studio", which is using NeMo as a backend. This however is still in an "alpha" stage. 

We are currently in the process of updating the synaptic model of nemo and providing an easier way of defining neural models without having to recompile any C++ code. We would be very keen to collaborate with you on this project as we definitely need extra hands to maintain NeMo alive :) 

Do you have any particular ideas in your mind?

Cheers,
Zaf

**Comment by PabloGN** [comment]
Thank you for your work!
I have tested NeMo only on CPU both on x86-64 and Raspberry Pi 3, with these options:
```
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DNEMO_TIMING_ENABLED=ON -DNEMO_CPU_OPENMP_ENABLED=ON
make
sudo make install
cd src/examples
./torus --cpu -n 2 -m 100 --benchmark
```
Results:
(PC i7) Speedup wrt real-time: 15.361
(RPi3) Speedup wrt real-time: 1.05319
For me it is very important the performance on Raspberry Pi 3. I am planning artificial vision with this hardware, so I need a couple of thousands of neurons. [With GeNN](https://github.com/genn-team/genn/pull/108) I got results better than real time with 1600 neurons and NeMo gives it with 2048. It depends on connectivity.
I also want to prepare a ROS node in a Docker container to encapsulate the network. See [Docker Hub](https://hub.docker.com/r/pablogn/rpi-ros-core-indigo/).
My aim go on the development of an autonomous robot (see [this article](http://dx.doi.org/10.1007/s12008-016-0313-8)).
Yes, we could collaborate, it can be very interesting :)

**Comment by zfountas** [comment]
Great, this looks quite interesting. So it seems that NeMo is already optimised enough for what you need right? The most important factor for the speed of these simulations is how many synapses you require in your architecture. Also, whether you need plasticity to be activated all the time.

**Comment by PabloGN** [comment]
Yes, maybe with STDP enabled it can be slower. I have run the same example under valgrind to find the bottlenecks and to insert more #pragma omp parallel for default(shared) but without deep knowledge of structures, arrays and sizes you can get less performance.
I do not know yet which is the proper configuration (delays, topology...) to get the behaviour I want, local connectivity might be better for performance, so I'll tell you...
